source 'https://rubygems.org'

gem 'activerecord', '~> 4.0.0'
gem 'activeresource', '~> 4.0.0'
gem 'actionmailer', '~> 4.0.0'
gem 'railties', '~> 4.0.2'

gem 'sqlite3'

gem 'carrierwave'
gem 'fog'
gem 'kaminari'
gem 'plupload-rails', '>= 1.1.0'

gem 'haml-rails', '>= 0.5.3'
gem 'jquery-rails', '>= 3.0.4'
gem 'sass-rails', '>= 4.0.1'
gem 'bootstrap_sass_rails'
gem 'simple_form'
