source 'https://rubygems.org'

gem 'activerecord', '~> 4.0.0'
gem 'activeresource', '~> 5.1.1'
gem 'actionmailer', '~> 4.0.0'
gem 'railties', '~> 4.0.0'

gem 'sqlite3'

gem 'carrierwave'
gem 'fog'
gem 'kaminari'
gem 'plupload-rails'

gem 'haml-rails'
gem 'jquery-rails'
gem 'sass-rails'
gem 'bootstrap_sass_rails'
gem 'simple_form'
