source 'https://rubygems.org'

gem 'activerecord', '~> 6.1.7', '>= 6.1.7.1'
gem 'activeresource', '~> 5.1.0'
gem 'actionmailer', '~> 6.1.7', '>= 6.1.7.1'
gem 'railties', '~> 6.1.7', '>= 6.1.7.1'

gem 'sqlite3'

gem 'carrierwave'
gem 'fog'
gem 'kaminari'
gem 'plupload-rails'

gem 'haml-rails'
gem 'jquery-rails', '>= 4.0.1'
gem 'sass-rails', '>= 5.0.8'
gem 'bootstrap_sass_rails'
gem 'simple_form', '>= 4.0.0'
